"""Tests for clean-ai-artifacts."""

import tempfile
from pathlib import Path
import pytest
import os

# Import directly from the source to ensure we test the local code
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))

from clean_ai_artifacts.cli import (
    clean_directory,
    is_ai_generated,
    is_binary_file,
    remove_emojis,
    DEFAULT_AI_MARKERS,
    DEFAULT_AI_SUFFIX,
)

class TestRemoveEmojis:
    def test_removes_simple_emoji(self):
        assert remove_emojis("Hello World \U0001F600") == "Hello World "

    def test_preserves_text(self):
        assert remove_emojis("Hello World") == "Hello World"

    def test_removes_multiple_emojis(self):
        result = remove_emojis("Test \U0001F600 test \U0001F600")
        assert result == "Test  test "

    def test_preserves_special_chars(self):
        text = "import * from 'react'; // #1 module"
        assert remove_emojis(text) == text

    def test_removes_skin_tone_emoji(self):
        # Thumbs up with medium skin tone
        assert remove_emojis("Nice job! \U0001F44D\U0001F3FD") == "Nice job! "

    def test_removes_zwj_family_emoji(self):
        # Family: Man, Woman, Girl, Boy (ZWJ sequence)
        family_emoji = "\U0001F468\u200d\U0001F469\u200d\U0001F467\u200d\U0001F466"
        assert remove_emojis(f"Family: {family_emoji}") == "Family: "

    def test_removes_flag_emoji(self):
        # Flag: United States
        assert remove_emojis("USA \U0001F1FA\U0001F1F8") == "USA "

    def test_removes_newer_unicode_emoji(self):
        # Ninja (added in Unicode 13.0)
        assert remove_emojis("Ninja \U0001F977") == "Ninja "

class TestIsAiGenerated:
    def test_detects_ai_suffix(self, tmp_path):
        ai_file = tmp_path / "notes_ai.md"
        ai_file.write_text("Some content", encoding="utf-8")
        assert is_ai_generated(ai_file, DEFAULT_AI_MARKERS, DEFAULT_AI_SUFFIX)

    def test_detects_ai_marker(self, tmp_path):
        ai_file = tmp_path / "notes.md"
        ai_file.write_text("Generated by AI\n\nSome content here", encoding="utf-8")
        assert is_ai_generated(ai_file, DEFAULT_AI_MARKERS, DEFAULT_AI_SUFFIX)

    def test_ignores_normal_file(self, tmp_path):
        normal_file = tmp_path / "README.md"
        normal_file.write_text("# My Project\n\nThis is a normal readme.", encoding="utf-8")
        assert not is_ai_generated(normal_file, DEFAULT_AI_MARKERS, DEFAULT_AI_SUFFIX)

class TestIsBinaryFile:
    def test_detects_binary(self, tmp_path):
        binary_file = tmp_path / "test.bin"
        binary_file.write_bytes(b"\x00\x01\x02\x03")
        assert is_binary_file(binary_file)

    def test_detects_text(self, tmp_path):
        text_file = tmp_path / "test.txt"
        text_file.write_text("Hello World", encoding="utf-8")
        assert not is_binary_file(text_file)

class TestCleanDirectory:
    def test_deletes_ai_files(self, tmp_path):
        ai_file = tmp_path / "notes_ai.md"
        ai_file.write_text("AI generated content", encoding="utf-8")
        
        # Create a README that should be IGNORED (Safety check)
        readme = tmp_path / "README.md"
        readme.write_text("Generated by AI inside readme", encoding="utf-8")

        stats = clean_directory(tmp_path, dry_run=False, clean_emojis=False, verbose=False)

        assert stats["deleted_files"] == 1
        assert not ai_file.exists()
        assert readme.exists() # IMPORTANT: Should NOT delete README

    def test_cleans_emojis(self, tmp_path):
        code_file = tmp_path / "app.py"
        code_file.write_text('print("Hello \U0001F600")', encoding="utf-8")

        stats = clean_directory(tmp_path, dry_run=False, clean_md=False, verbose=False)

        assert stats["cleaned_files"] == 1
        assert code_file.read_text(encoding="utf-8") == 'print("Hello ")'

    def test_dry_run_preserves_files(self, tmp_path):
        ai_file = tmp_path / "notes_ai.md"
        ai_file.write_text("AI content", encoding="utf-8")

        stats = clean_directory(tmp_path, dry_run=True, verbose=False)

        assert stats["deleted_files"] == 1
        assert ai_file.exists()

    def test_skips_node_modules(self, tmp_path):
        nm_dir = tmp_path / "node_modules" / "some-package"
        nm_dir.mkdir(parents=True)
        ai_file = nm_dir / "notes_ai.md"
        ai_file.write_text("AI content", encoding="utf-8")

        stats = clean_directory(tmp_path, dry_run=False, verbose=False)

        assert stats["deleted_files"] == 0
        assert ai_file.exists()
